### ISSUE TITLE
Error when build with vue-tsc

### ISSUE THREAD

**Issue by Yyooogurt** [smastrom/vue-collapsed#13]
**Terminal command:** vue-tsc --noEmit && vite build  --mode production

node_modules/vue-collapsed/dist/index.d.ts:1:15 - error TS1005: ',' expected.

`1 import { type PropType } from 'vue';`
                   

If I delete the word `type` in the index.d.ts, the build runs normally. Please tell me how to fix this error so that you don't have to go to the root of the add-on after each update of the packages.

Vue-collapsed version - 1.1.3

**Comment by smastrom** [comment]
Hi Yogurt, make sure you have added this property to your `tsconfig.json`:

```json
{
   "compilerOptions": {
      "skipLibCheck": true,
   },
}
```

**Comment by smastrom** [comment]
Hi Yogurt, try to add `skipLibCheck` to your `tsconfig.json`:

```json
{
   "compilerOptions": {
      "skipLibCheck": true,
   },
}
```

**Comment by smastrom** [comment]
You can try to add it to your CLI command: `vue-tsc --noEmit --skipLibCheck && vite build --mode production`

**Comment by Yyooogurt** [comment]
> You can try to add it to your CLI command: `vue-tsc --noEmit --skipLibCheck && vite build --mode production`

Good idea, but the result is the same (

**Comment by smastrom** [comment]
I had another good idea, try to update to the latest version and check if the error is still there:

`pnpm add vue-collapsed@latest`

**Comment by Yyooogurt** [comment]
> I had another good idea, try to update to the latest version and check if the error is still there:
> 
> `pnpm add vue-collapsed@latest`
