### ISSUE TITLE
Does not work for iOS

### ISSUE THREAD

**Issue by Lamerchun** [smastrom/vue-collapsed#16]

**Comment by smastrom** [comment]
Hi @Lamerchun, I suspect your issue is not related with this package as I have no probems expanding/collapsing all the examples of [demo website](https://vue-collapsed.netlify.app) with my iPhone.
 
 Anyways, I'm happy to help you out if you can provide me some sort of reproduction on [StackBlitz](https://stackblitz.com) or [CodeSandbox](https://codesandbox.io).

**Comment by Lamerchun** [comment]
Hi,

Thanknyoi so much for the quick response.

I am using iPhone 14 Pro with the latest iOS.

On your demo page collapsing works. But it is not animated as it should. Using mac os, with works and animation is smooth.

Hope it helps you finding the issue. I would love to use your package.

KR
Tuan

Von meinem iPhone gesendet

Am 12.09.2023 um 23:12 schrieb Simone Mastromattei ***@***.***>:

﻿

Hi @Lamerchun<https://github.com/Lamerchun>, I suspect your issue is not related with this package as I have no probems expanding/collapsing all the examples of demo website<https://vue-collapsed.netlify.app> with my iPhone.

Anyways, I'm happy to help you out if you can provide me some sort of reproduction on StackBlitz<https://stackblitz.com> or CodeSandbox<https://codesandbox.io>.

**Comment by smastrom** [comment]
If the animation is laggy, that's maybe because you have [Low Power Mode](https://support.apple.com/en-us/101604) enabled?

**Comment by Lamerchun** [comment]
There is no animation at all. I have 23% and power plugged right now. Will try it later again. Works on my iPhone 8 though. 

Btw. is it possible to male the animation horizontally from width 0 to auto?

**Comment by smastrom** [comment]
If the expand/collapse works but you see no transition, that's maybe because you have enabled [reduced motion](https://www.idownloadblog.com/2019/01/28/turn-off-animations-iphone-ipad/)?

**Comment by Lamerchun** [comment]
Ah yes. This is true. Didnt know this is supported. Great! Thanks

**Comment by Lamerchun** [comment]
Works when disabled motion reduction. 👍🏻
