### ISSUE TITLE
[BUG] Sometimes it stays in mode "expanding"

### ISSUE THREAD

**Issue by Matoseb** [smastrom/vue-collapsed#20]
On some occasion, seamingly random, the Collapse stays in "expanding" mode.
This prevents the event expanded to trigger and makes the data-collapse value stay as "expanding".

**Comment by smastrom** [comment]
Hi @Matoseb, I'm sorry to hear that. However, the issue sounds too generic and there isn't much I can do without a reproduction. Please provide one and I'll be happy to investigate and fix.

**Comment by IGezekia** [comment]
To replicate try to interact with child element during expanding mode. In my case i have dropdown menu inside collapse container and if i click dropdown while collapse component still expanding I get the bug.
