### ISSUE TITLE
SSR problem: layout shift

### ISSUE THREAD

**Issue by zhaivoronok** [smastrom/vue-collapsed#21]
In Nuxt.js from server I get plain html without base styles (like **display: none;** if content is collapsed), and styles applied only on mounted. It will be great if proper styles will come from server so no layout shift will be there.

**Comment by smastrom** [comment]
Hi @zhaivoronok, you're right. This is because I made the mistake to not setup the playground on Nuxt (like I did for my other packages).

Expect a fix in the afternoon.
