### ISSUE TITLE
When section is expanded, overflow: hidden (among other differences) is added in Firefox but not Chrome

### ISSUE THREAD

**Issue by xenia1** [smastrom/vue-collapsed#24]
Hi,

I ran into the following issue in Firefox (v 124-124.0.1): 

I have a dropdown within a collapsible section. The part of the dropdown which is outside the slide container is cut off in Firefox but not in Chrome:

a) Firefox -
![Screenshot 2024-03-27 at 3 57 43 PM](https://github.com/smastrom/vue-collapsed/assets/14450967/d27bb8fc-a347-4208-b05d-57d5df60f6dc)

b) Chrome - 
![Screenshot 2024-03-27 at 4 00 49 PM](https://github.com/smastrom/vue-collapsed/assets/14450967/85fce62f-1d8b-4c75-9b86-7b01abc098c1)

It looks like the reason is that in Firefox, some additional CSS classes are added which are not added in Chrome. Additionally, the state is not the same (`expanded`/`collapsed` in Chrome vs `expanding`/`collapsing` in Firefox):

a) Firefox -
![Screenshot 2024-03-27 at 4 11 48 PM](https://github.com/smastrom/vue-collapsed/assets/14450967/f424274f-5ae8-40c3-9608-d5509c3a9162)

b) Chrome - 
<img width="469" alt="Screenshot 2024-03-27 at 4 11 20 PM" src="https://github.com/smastrom/vue-collapsed/assets/14450967/9e83c6ca-8076-4cd9-be8b-346019d3a753">

### **Replication**
You can see this effect in the[ stackblitz link](https://stackblitz.com/edit/vue-dmjqey?file=src%2FApp.vue) provided on the github readme if you inspect one of the sections:

a) Firefox -
![Screenshot 2024-03-27 at 3 47 51 PM](https://github.com/smastrom/vue-collapsed/assets/14450967/08015ebd-9b46-487e-b29c-d7cdb7a7e19f)

b) Chrome - 
<img width="1694" alt="Screenshot 2024-03-27 at 3 47 38 PM" src="https://github.com/smastrom/vue-collapsed/assets/14450967/3ff001fc-7976-4923-881b-0cf3ba0c8c88">

Please can anything be done about this so that Firefox is consistent with Chrome, i.e. it doesn't have those additional classes? Or is there an appropriate workaround I can use? 

Thanks!

**Comment by xenia1** [comment]
Updated to latest version  (1.3.1) and it's fixed 🤦‍♀️. 

Same cause/ fix as for this - https://github.com/smastrom/vue-collapsed/issues/23 ?

**Comment by smastrom** [comment]
> Updated to latest version (1.3.1) and it's fixed 🤦‍♀️.
> 
> Same cause/ fix as for this - #23 ?

Yeah, versions < 1.3.1 are broken on Firefox >= 124. Installing the latest version will fix everything 😃
