### ISSUE TITLE
Collapse transition never finishing for custom zoom of the page

### ISSUE THREAD

**Issue by krzysztof-krzeszewski** [smastrom/vue-collapsed#26]
In the code the onCollapse function is called only when the following condition is satisfied:
```
    if (baseHeight.value === getComputedHeight(collapseRef)) {
        onCollapsed()
    }
```

However the computed height of the element is not always exact.

For instance I have an element that is `42px` in height. When running in chrome, when user zooms the page out to 90% the computed height value is no longer `42px` but `41.9965px`. So this condition fails, and the state of the collapsible is never updated. 

This is a subpixel rendering issue that caused it, so I think a proper solution would be to trim/round the computed value. I don't think a sub-pixel precision is required and it would fix this issue.

On an unrelated note: floating point numbers shouldn't be compared using equality operator.

**Comment by smastrom** [comment]
Hi @krzysztof-krzeszewski, thanks for raising this issue. Although I couldn't reproduce this on lastest Chrome version on macOS (the scaling is at 75% in the video below but I tried with any other percentage):

https://github.com/smastrom/vue-collapsed/assets/60471784/ab8b711d-b873-46f9-b971-6bfbc0719f0a

You're correct and this should definitely be made bullet-proof. Already working on it.

**Comment by smastrom** [comment]
Ah ok I see, please let me know if it works as expected here: [https://1-3-2.vue-collapsed.pages.dev/](https://1-3-2.vue-collapsed.pages.dev/)

**Comment by krzysztof-krzeszewski** [comment]
I think you might have made a mistake when copying the coniditon over.
Now it never finishes collapsing even when the page isn't zoomed out.

![image](https://github.com/smastrom/vue-collapsed/assets/143795192/35652a34-cec7-411c-958a-188e1ef6ad52)

**Comment by krzysztof-krzeszewski** [comment]
It's working fine for me.
