### ISSUE TITLE
Default collapse animation not working anymore on chrome

### ISSUE THREAD

**Issue by Azurox** [smastrom/vue-collapsed#31]
I tested on multiple device, it looks like the default Collapse animation stopped working on Chrome

```html 
<Collapse :when="isExpanded">
    ...
</Collapse>
```

A workaround is using a custom transition
```html
<Collapse :when="isExpanded" class="v-collapse">
  ....
</Collapse>

<style>
.v-collapse {
  transition: height 300ms ease-out;
  /* or transition: height var(--vc-auto-duration) ease-in-out */
}
</style>
```

Did not have time to investigate but it looks like the appended transition is `all` for some reason, instead of `height var(--vc-auto-duration) etc...`

Thanks

**Comment by smastrom** [comment]
Hi @Azurox, thanks for reporting. Yeah it seems that now Blink alignes with Gecko regarding the default transition value which is now `all` instead of `all 0s ease 0s`. Will merge a fix in the next half hour.
