### ISSUE TITLE
Named export 'Collapse' not found.

### ISSUE THREAD

**Issue by mrleblanc101** [smastrom/vue-collapsed#6]
> Named export 'Collapse' not found. The requested module 'file:///Users/sleblanc/Github/mrleblanc101.github.io/node_modules/vue-collapsed/dist/index.umd.js' is a CommonJS module, which may not support all module.exports as named exports.

**Comment by mrleblanc101** [comment]
This is in a Nuxt 3 app using Vite.js 3

**Comment by smastrom** [comment]
Hi @mrleblanc101, I crated a basic usage example using Nuxt 3 with SSR.

[https://stackblitz.com/edit/nuxt-starter-zfiqcm?file=app.vue](https://stackblitz.com/edit/nuxt-starter-zfiqcm?file=app.vue)

Please let me know if you still have issues.

**Comment by mrleblanc101** [comment]
@smastrom Thanks for the quick reply.
Sorry, I wasn't clear.
I have it working with `yarn dev` (dev mode).
But not with `yarn generate` (production mode for static site generation.

**Comment by mrleblanc101** [comment]
Why do you do `export { s as Collapse };` which require use to import like this `import { Collapse } from 'vue-collapsed';`
Instead of `export default collapse` which would allow us to do `import Collapse from 'vue-collapse'` ?

**Comment by mrleblanc101** [comment]
Wait, I think it work with `1.1.1` that you just released 15min ago.
Or maybe the Nuxt server needed a break 🤔 
Thanks anyway !
